### ISSUE TITLE
Youtube API change

### ISSUE THREAD

**Issue by Deux9** [yhcting/netmbuddy#7]
Please please add the new API so we can keep using this. It's the only for me to listen to listen to various sleep inducing streams with the screen turned of.

**Comment by TT44bb** [comment]
Would be nice indeed. Really like your app.

**Comment by brendes** [comment]
I agree. This app was incredibly convenient but appears to be broken.

**Comment by mdaniel** [comment]
I am experiencing "Error in accessing network" when trying to search, but I am not certain if I have this issue or a new one. Can one of the prior commenters please elaborate on what you mean by "broken"?

**Comment by TT44bb** [comment]
Youtube changed their API. This means this app can't work anymore, at all. There will probably be various different errors depending on what you try to do.
At the moment there simply is no "other" issue because nothing is supposed to work anyway. I suggest you wait for this issue here to resolved and only if your problem persists then report it.
But I fear the app looks abandoned and likely won't be updated by the original author.
Someone else could pick up the task in principle, but I'm not sure how realistic that is.

**Comment by TT44bb** [comment]
Oops, sorry, should have just tested: Seems playing existing playlists works. So they didn't change all of their API after all. When searching I get the same error as you.

**Comment by yhcting** [comment]
YTHacker is also updated as Youtube web api is changed.
(So, not all video is available as it was.)
And in terms of data api, I am trying to catch up.
At this moment, premature and testing codes are committed.
And code will be continuously patched for better UI based on YouTube data api v3.

**Comment by yhcting** [comment]
There are two problems.

* I'm lazy and busy to spend enough time to this project.
Please understand it and wait with patient.
Project will be updated/improved even if it's very slow, because I'm also using this app for myself.

* Google blocks NetMBuddy from GooglePlayStore.
So, I think I have to consider other way to release APK.

**Comment by TT44bb** [comment]
I think in principle this app violates their terms of service or something. Whatever. I got it from the F-Droid repo, this works quite nicely.

**Comment by yhcting** [comment]
App supports Youtube data api v3 now. But still premature... Anyway...
